// ? user types
export const SET_USER = 'SET_USER';
export const SET_USER_LOADING = 'SET_USER_LOADING';
export const SET_USER_ERRORS = 'SET_USER_ERRORS';
export const SET_USER_NO_ERRORS = 'SET_USER_NO_ERRORS';
// ? category types
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_CATEGORIES_ERRORS = 'SET_CATEGORIES_ERRORS';
export const SET_CATEGORIES_LOADING = 'SET_CATEGORIES_LOADING';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const CATEGORY_STATUS = 'CATEGORY_STATUS';
// ? post types
export const SET_POSTS = 'SET_POSTS';
export const SET_POSTS_ERRORS = 'SET_POSTS_ERRORS';
export const SET_POSTS_LOADING = 'SET_POSTS_LOADING';
export const ADD_POST = 'ADD_POST';
export const UPDATE_POST = 'UPDATE_POST';
export const DELETE_POST = 'DELETE_POST';
export const SET_SINGLE_POST = 'SET_SINGLE_POST';
// ? profile types
export const SET_PROFILE = 'PROFILE_CREATE';
export const SET_PROFILE_ERRORS = 'SET_PROFILE_ERRORS';
export const SET_PROFILE_LOADING = 'SET_PROFILE_LOADING';
export const SET_PROFILE_PICTURE = 'SET_PROFILE_PICTURE';

// ? loading

export const SET_LOADING = 'SET_LOADING';

// ? public types
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_SINGLE_CATEGORY = 'FETCH_SINGLE_CATEGORY';
export const FETCH_POSTS = 'FETCH_POSTS ';
export const POST_LIKE_UNLIKE = 'POST_LIKE_UNLIKE';
export const FETCH_RECENT_POSTS = 'FETCH_RECENT_POSTS';
export const FETCH_SINGLE_POST = 'FETCH_SINGLE_POST';
export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const ADD_COMMENT = 'ADD_COMMENT';
export const SET_COMMENT_ERRORS = 'SET_COMMENT_ERRORS';
